card_types:
  cards:
    unity_folder: 'output'
    frame_re: '.\d$'
    anim_folder: animation
    outputs:
      - original
      - animated
      - small
      - medium
      - mediumj
    composite: ''
  heroes:
    unity_folder: 'heroes'
    frame_re: '_.\d*$'
    anim_folder: animation
    outputs:
      - original
      - animated
    composite: ''
  cardbacks:
    unity_folder: 'cardbacks'
    frame_re: '_.\d*$'
    anim_folder: animation
    outputs:
      - original
      - animated
      - animated_temp
      - small
      - medium
      - mediumj
      - icons/small
      - icons/medium
      - icons/large
    composite: 'watermark-cards-forgenerator.png'
processes: 11

# from unityproject/Assets/Scripts/Locale.cs
# this actually doens't control which locales will be generated but
# to generate a locale it needs to be in this list
locale:
  - enUS
  - enGB
  - frFR
  - deDE
  - koKR
  - esES
  - esMX
  - ruRU
  - zhTW
  - zhCN
  - itIT
  - ptBR
  - plPL
  - ptPT